# Dockerfile.batch
FROM python:3.9-slim
WORKDIR /app

RUN pip install pandas s3fs pyarrow sqlalchemy psycopg2-binary

# Copy script vào
COPY batch/compaction.py .

# Chạy script
CMD ["python", "compaction.py"]