FROM python:3.9-slim
WORKDIR /app

RUN pip install fastapi uvicorn kafka-python s3fs pandas google-genai pyarrow sqlalchemy psycopg2-binary

COPY api/ .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]