FROM python:3.9-slim
WORKDIR /app
COPY ingestion/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pyarrow s3fs pandas kafka-python

COPY ingestion/ .
CMD ["python", "binance_producer.py"]